Computation on NumPy arrays can be very **fast**, or it can be very **slow**. The **key** to making it fast is to use **vectorized operations**, generally implemented through NumPy's universal functions (ufuncs). This section motivates the need for **NumPy's ufuncs**, which can be used to make **repeated calculations** on array elements much more efficient. It then introduces many of the most common and useful **arithmetic ufuncs** available in the NumPy package.

## 1. The Slowness of Loops

The relative **sluggishness(迟缓)** of Python generally manifests itself in situations where many small operations are being repeated – for instance looping over arrays to operate on each element.

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    # Return a new array of given shape and type, without initializing entries.
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [2]:
# Calculate running time
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.05 s ± 23.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


This seems almost absurdly slow. If we were working in **compiled code** instead, this **type specification** would be known before the code executes and the result could be computed much more **efficiently**.

## 2. Introducing UFuncs

In [4]:
values

array([6, 1, 4, 4, 8])

In [5]:
# vectorized operation comparison
print(compute_reciprocals(values))
print(1.0 / values)

[ 0.16666667  1.          0.25        0.25        0.125     ]
[ 0.16666667  1.          0.25        0.25        0.125     ]


In [6]:
# Calculate running time(vectorized operation)
%timeit (1.0 / big_array)

2.84 ms ± 63.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Vectorized operations** in NumPy are implemented **via ufuncs**, whose main purpose is to **quickly execute repeated** operations on values in NumPy arrays.

In [7]:
np.arange(5) / np.arange(1, 6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

And **ufunc operations** are not limited to **one-dimensional arrays**–they can also act on **multi-dimensional arrays** as well:

In [8]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

Computations using **vectorization** through ufuncs are nearly always **more efficient** than their counterpart implemented using Python loops, especially as the **arrays grow in size**.

## 2. Exploring NumPy's UFuncs

**Ufuncs** exist in two flavors: **unary ufuncs**, which operate on a single input, and **binary ufuncs**, which operate on two inputs. 

#### 1. Array arithmetic

In [9]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


There is also a **unary ufunc** for **negation**, and a ** operator for **exponentiation**, and a % operator for **modulus**:

In [10]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In addition, these can be **strung together** however you wish, and the **standard order** of operations is **respected**:

In [11]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Each of these **arithmetic operations** are simply convenient **wrappers** around specific functions built into NumPy; for example, the **+** operator is a wrapper for the **add** function:

In [12]:
np.add(x, 2)

array([2, 3, 4, 5])

In [14]:
# + -> np.add  (Addition)
# - -> np.substract (Subtraction)
# - -> np.negative (Unary negation)
# * -> np.multiply (Multiplication)
# / -> np.divide (Division)
# // -> np.floor_divide (Floor division)
# ** -> np.power (Exponentiation)
# % -> np.mod (Modulus/remainder)

#### 2. Absolute value

In [16]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is **np.absolute**, which is also available under the alias **np.abs**:

In [18]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [19]:
np.abs(x)

array([2, 1, 0, 1, 2])

This ufunc can also handle **complex data(复数)**, in which the absolute value returns the **magnitude**:

In [20]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([ 5.,  5.,  2.,  1.])

#### 3. Trigonometric functions(三角函数)

In [21]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# 在指定的间隔内返回均匀间隔的数字。
theta = np.linspace(0, np.pi, 3)

In [22]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [ 0.          1.57079633  3.14159265]
sin(theta) =  [  0.00000000e+00   1.00000000e+00   1.22464680e-16]
cos(theta) =  [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
tan(theta) =  [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


The values are computed to within **machine precision**, which is why values that should be **zero** do not always hit **exactly zero**. **Inverse trigonometric** functions are also available:

In [23]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [ 3.14159265  1.57079633  0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### 4. Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the **exponentials**:

In [24]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [  2.71828183   7.3890561   20.08553692]
2^x   = [ 2.  4.  8.]
3^x   = [ 3  9 27]


The inverse of the **exponentials**, the **logarithms**, are also available. The basic **np.log** gives the **natural logarithm**; if you prefer to compute the **base-2 logarithm** or the **base-10 logarithm**, these are available as well:

In [25]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x)  = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]


There are also some specialized versions that are useful for maintaining **precision** with very small input:

In [26]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [ 0.          0.0010005   0.01005017  0.10517092]
log(1 + x) = [ 0.          0.0009995   0.00995033  0.09531018]


When x is very **small**, these functions give more **precise values** than if the raw **np.log** or **np.exp** were to be used.

#### 5. Specialized ufuncs

Another excellent source for more specialized and obscure ufuncs is the submodule **scipy.special**. If you want to compute some **obscure mathematical function** on your data, chances are it is implemented in **scipy.special**. There are far too many functions to list them all, but the following snippet shows a couple that might come up in a statistics context:

In [27]:
from scipy import special

In [28]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [  1.00000000e+00   2.40000000e+01   3.62880000e+05]
ln|gamma(x)| = [  0.           3.17805383  12.80182748]
beta(x, 2)   = [ 0.5         0.03333333  0.00909091]


In [29]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [ 0.          0.32862676  0.67780119  0.84270079]
erfc(x) = [ 1.          0.67137324  0.32219881  0.15729921]
erfinv(x) = [ 0.          0.27246271  0.73286908         inf]


There are many, many more ufuncs available in both **NumPy** and **scipy.special**. 

#### 6. Advanced Ufunc Features

For all ufuncs, this can be done using the **out** argument of the function:

In [30]:
x = np.arange(5)
y = np.empty(5)
# out=y
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


In [32]:
print("x =", x)
y = np.zeros(10)
print("y = ", y)
np.power(2, x, out=y[::2])
print(y)

x = [0 1 2 3 4]
y =  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


If we had instead written **y[::2] = 2 ** x**, this would have resulted in the creation of a **temporary array** to hold the results of **2 ** x**, followed by a second operation **copying those values into the y array**. This doesn't make much of a **difference** for such a **small computation**, but for very **large arrays** the memory savings from careful use of the out argument can be **significant**.

#### 7. Aggregates

For example, calling **reduce** on the **add ufunc** returns the **sum** of all elements in the array:

In [33]:
x = np.arange(1, 6)
print("x = ", x)
np.add.reduce(x)

x =  [1 2 3 4 5]


15

Similarly, calling **reduce** on the **multiply ufunc** results in the product of all array elements:

In [34]:
np.multiply.reduce(x)

120

If we'd like to **store** all the **intermediate results** of the **computation**, we can instead use accumulate:

In [35]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [36]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Note that for these particular cases, there are dedicated NumPy functions to compute the results **(np.sum, np.prod, np.cumsum, np.cumprod)**.

#### 6. Outer products

Finally, any **ufunc** can **compute the output of all pairs of two different inputs** using the **outer** method. This allows you, in one line, to do things like create a multiplication table:

In [37]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

The **ufunc.at** and **ufunc.reduceat** methods, which we'll explore in Fancy Indexing, are very helpful as well.

Another is **broadcasting**. operate between arrays of different sizes and shapes, a set of operations